version: 2.1

orbs:
  maven: circleci/maven@1.0.0

workflows:
  jobs:
    maven-orb-test:
      executor:
        name: maven/default
        tag: '11.0.6'
      steps:
        - checkout
        - maven/with_cache:
            maven_command: mvn compile
            steps:
              - run: mvn compile
